/* AUTO-GENERATED by scripts/build-images.js — do not edit by hand.
   CT_MEDIA      : resource id -> { cover?, slideNum }
   CT_SLIDE_LINKS: slide # -> [{text,url}]  (EVERY slide's links)
   CT_SLIDE_COUNT: total slides (gallery uses assets/slides/slide-NNN.jpg)
   Re-run: node scripts/build-images.js */
const CT_MEDIA = {
 "who-do-we-become": {
  "slideNum": 7,
  "cover": "assets/img/auto/who-do-we-become.jpg"
 },
 "octavia-thousands": {
  "slideNum": 7,
  "cover": "assets/img/auto/octavia-thousands.jpg"
 },
 "truth-mandala": {
  "slideNum": 13,
  "cover": "assets/img/auto/truth-mandala.jpg"
 },
 "pain-as-compassion": {
  "slideNum": 16
 },
 "emotions-of-world": {
  "slideNum": 8
 },
 "vandana-shiva": {
  "slideNum": 10,
  "cover": "assets/img/auto/vandana-shiva.jpg"
 },
 "sadhguru-soil": {
  "slideNum": 11,
  "cover": "assets/img/auto/sadhguru-soil.jpg"
 },
 "siara-edmond": {
  "slideNum": 12,
  "cover": "assets/img/auto/siara-edmond.jpg"
 },
 "on-being-ecology": {
  "slideNum": 16
 },
 "children-citizens": {
  "slideNum": 18
 },
 "intersectionality": {
  "slideNum": 21
 },
 "charles-white": {
  "slideNum": 19,
  "cover": "assets/img/auto/charles-white.jpg"
 },
 "alicia-keys-culture": {
  "slideNum": 19,
  "cover": "assets/img/auto/alicia-keys-culture.jpg"
 },
 "brave-space": {
  "slideNum": 27
 },
 "land-acknowledgement": {
  "slideNum": 23
 },
 "cat-brooks-heart-sing": {
  "slideNum": 23
 },
 "crt-definition": {
  "slideNum": 37
 },
 "microaggressions-nadal": {
  "slideNum": 31
 },
 "me-bag-life-like-mine": {
  "slideNum": 44
 },
 "power-definition": {
  "slideNum": 45,
  "cover": "assets/img/auto/power-definition.jpg"
 },
 "titus-kaphar-amend": {
  "slideNum": 59,
  "cover": "assets/img/auto/titus-kaphar-amend.jpg"
 },
 "visible-thinking": {
  "slideNum": 62,
  "cover": "assets/img/auto/visible-thinking.jpg"
 },
 "disclaimers-disney-wb": {
  "slideNum": 61
 },
 "mini-design-project": {
  "slideNum": 67,
  "cover": "assets/img/auto/mini-design-project.jpg"
 },
 "justice-x-design": {
  "slideNum": 66,
  "cover": "assets/img/auto/justice-x-design.jpg"
 },
 "gay-feminism": {
  "slideNum": 69,
  "cover": "assets/img/auto/gay-feminism.jpg"
 },
 "art-build": {
  "slideNum": 71,
  "cover": "assets/img/auto/art-build.jpg"
 },
 "enslaved-who-resisted": {
  "slideNum": 74,
  "cover": "assets/img/auto/enslaved-who-resisted.jpg"
 },
 "mari-copeny": {
  "slideNum": 73,
  "cover": "assets/img/auto/mari-copeny.jpg"
 },
 "alphabet-rockers": {
  "slideNum": 85,
  "cover": "assets/img/auto/alphabet-rockers.jpg"
 },
 "image-theatre": {
  "slideNum": 95
 },
 "becoming-abolitionists": {
  "slideNum": 94,
  "cover": "assets/img/auto/becoming-abolitionists.jpg"
 },
 "steve-locke-grays": {
  "slideNum": 99,
  "cover": "assets/img/auto/steve-locke-grays.jpg"
 },
 "music-apps": {
  "slideNum": 101
 },
 "tge-myths": {
  "slideNum": 108,
  "cover": "assets/img/auto/tge-myths.jpg"
 },
 "crc-scorecard": {
  "slideNum": 121
 },
 "broadening-community": {
  "slideNum": 19,
  "cover": "assets/img/auto/broadening-community.jpg"
 },
 "rhythm-resistance": {
  "slideNum": 22,
  "cover": "assets/img/auto/rhythm-resistance.jpg"
 },
 "poetry-as-container": {
  "slideNum": 22,
  "cover": "assets/img/auto/poetry-as-container.jpg"
 },
 "arat-brave-space": {
  "slideNum": 26
 },
 "amber-crowell-love": {
  "slideNum": 28,
  "cover": "assets/img/auto/amber-crowell-love.jpg"
 },
 "chipko-movement": {
  "slideNum": 29,
  "cover": "assets/img/auto/chipko-movement.jpg"
 },
 "black-history-origins": {
  "slideNum": 34,
  "cover": "assets/img/auto/black-history-origins.jpg"
 },
 "csuf-pulled-teachers": {
  "slideNum": 35
 },
 "growth-mindset-race": {
  "slideNum": 36,
  "cover": "assets/img/auto/growth-mindset-race.jpg"
 },
 "distorted-history": {
  "slideNum": 37
 },
 "ethnic-studies-history": {
  "slideNum": 42,
  "cover": "assets/img/auto/ethnic-studies-history.jpg"
 },
 "ethnic-studies-tk5": {
  "slideNum": 46,
  "cover": "assets/img/auto/ethnic-studies-tk5.jpg"
 },
 "wanda-watson-freedom": {
  "slideNum": 46,
  "cover": "assets/img/auto/wanda-watson-freedom.jpg"
 },
 "vamos-a-leer": {
  "slideNum": 47
 },
 "dey-problem-finders": {
  "slideNum": 56,
  "cover": "assets/img/auto/dey-problem-finders.jpg"
 },
 "carlsson-paige-play": {
  "slideNum": 56,
  "cover": "assets/img/auto/carlsson-paige-play.jpg"
 },
 "media-critics": {
  "slideNum": 60,
  "cover": "assets/img/auto/media-critics.jpg"
 },
 "design-thinking-process": {
  "slideNum": 64,
  "cover": "assets/img/auto/design-thinking-process.jpg"
 },
 "collaborative-planning": {
  "slideNum": 68,
  "cover": "assets/img/auto/collaborative-planning.jpg"
 },
 "baldwin-hate-pain": {
  "slideNum": 69,
  "cover": "assets/img/auto/baldwin-hate-pain.jpg"
 },
 "blm-week-of-action": {
  "slideNum": 72,
  "cover": "assets/img/auto/blm-week-of-action.jpg"
 },
 "prohibited-concepts": {
  "slideNum": 75
 },
 "art-social-movements": {
  "slideNum": 76,
  "cover": "assets/img/auto/art-social-movements.jpg"
 },
 "florida-teen-stonewall": {
  "slideNum": 78,
  "cover": "assets/img/auto/florida-teen-stonewall.jpg"
 },
 "connect-to-movements": {
  "slideNum": 79
 },
 "teach-ins": {
  "slideNum": 79
 },
 "rights-of-child": {
  "slideNum": 87,
  "cover": "assets/img/auto/rights-of-child.jpg"
 },
 "youth-activism-resources": {
  "slideNum": 90
 },
 "divest-from-sros": {
  "slideNum": 92,
  "cover": "assets/img/auto/divest-from-sros.jpg"
 },
 "drama-games": {
  "slideNum": 95
 },
 "growth-forms-nature": {
  "slideNum": 98,
  "cover": "assets/img/auto/growth-forms-nature.jpg"
 },
 "music-other-subjects": {
  "slideNum": 102,
  "cover": "assets/img/auto/music-other-subjects.jpg"
 },
 "hesitant-students": {
  "slideNum": 104
 },
 "healthy-music-diet": {
  "slideNum": 101
 },
 "gender-history": {
  "slideNum": 107
 },
 "thorn-quote": {
  "slideNum": 110,
  "cover": "assets/img/auto/thorn-quote.jpg"
 },
 "banned-books-why": {
  "slideNum": 41,
  "cover": "assets/img/auto/banned-books-why.jpg"
 },
 "arts-for-anxiety": {
  "slideNum": 112,
  "cover": "assets/img/auto/arts-for-anxiety.jpg"
 },
 "making-learning-visible": {
  "slideNum": 125
 },
 "girls-inc-eureka": {
  "slideNum": 128
 }
};
const CT_SLIDE_LINKS = {
 "8": [
  {
   "text": "here",
   "url": "https://jeffyasinchuk.ca/2021/06/13/our-truth-mandala-reality/"
  }
 ],
 "10": [
  {
   "text": "7 minute video",
   "url": "https://www.youtube.com/watch?v=QBciZhOOr-8"
  }
 ],
 "12": [
  {
   "text": "Oakland Youth Poet Laureate",
   "url": "https://www.youtube.com/watch?v=XuNWIlW5Srk&list=PLvbGlEzD3pCCCPZ7v5gMp6qofiK01qH4J&index=40"
  }
 ],
 "13": [
  {
   "text": "TRUTH MANDALA",
   "url": "https://vimeo.com/60909609?embedded=false&source=vimeo_logo&owner=16803648"
  }
 ],
 "14": [
  {
   "text": "video",
   "url": "https://vimeo.com/60909609?embedded=false&source=vimeo_logo&owner=16803648"
  }
 ],
 "16": [
  {
   "text": "On Being Project: Ecology and Nature",
   "url": "https://onbeing.org/libraries/ecology-nature/"
  }
 ],
 "18": [
  {
   "text": "Children Are Citizens",
   "url": "https://pz.harvard.edu/projects/children-are-citizens"
  },
  {
   "text": "Research story",
   "url": "https://www.gse.harvard.edu/news/uk/15/04/kid-nation#sthash.1V23Ubty.dpuf"
  }
 ],
 "19": [
  {
   "text": "Charles White: A Retrospective, at MoMA,",
   "url": "https://www.moma.org/calendar/exhibitions/3930?locale=en"
  }
 ],
 "20": [
  {
   "text": "https://drcrystallaura.com/",
   "url": "https://drcrystallaura.com/"
  }
 ],
 "21": [
  {
   "text": "TheOpportunityAgenda",
   "url": "https://www.opportunityagenda.org/explore/resources-publications/ten-tips-putting-intersectionality-practice"
  }
 ],
 "22": [
  {
   "text": "Rhythm and Resistance: A Conversation About Teaching and Writing Poetry",
   "url": "https://www.youtube.com/watch?v=Py114WsQr9g"
  },
  {
   "text": "Where Do You Know From?",
   "url": "https://maifeminism.com/where-do-you-know-from-an-exercise-in-placing-ourselves-together-in-the-classroom/"
  }
 ],
 "23": [
  {
   "text": "Dr. Nicole Lim",
   "url": "https://cimcc.org/"
  },
  {
   "text": "https://native-land.ca",
   "url": "https://native-land.ca"
  }
 ],
 "26": [
  {
   "text": "antiracistartteachers.org",
   "url": "http://antiracistartteachers.org"
  },
  {
   "text": "newsletter",
   "url": "https://mailchi.mp/8a6be50702f8/anti-racist-art-teachers-august-newsletter-5442905"
  }
 ],
 "27": [
  {
   "text": "safe space",
   "url": "https://antiracistartteachers.us6.list-manage.com/track/click?u=b58ca90785ee2bac300adbfa8&id=3c25cbc567&e=0ab62f37f1"
  },
  {
   "text": "brave space",
   "url": "https://antiracistartteachers.us6.list-manage.com/track/click?u=b58ca90785ee2bac300adbfa8&id=471241bbc2&e=0ab62f37f1"
  },
  {
   "text": "The Art of Effective Facilitation: Reflections From Social Justice Educators",
   "url": "https://antiracistartteachers.us6.list-manage.com/track/click?u=b58ca90785ee2bac300adbfa8&id=39ac0bdbc2&e=0ab62f37f1"
  },
  {
   "text": "framework of brave spaces",
   "url": "https://antiracistartteachers.us6.list-manage.com/track/click?u=b58ca90785ee2bac300adbfa8&id=52da4671c6&e=0ab62f37f1"
  }
 ],
 "28": [
  {
   "text": "Anti-Racism: A Public Professional Learning Community Webinar Series",
   "url": "https://www.antiracistartteachers.org/anti-racist-art-resources/professional-development"
  }
 ],
 "29": [
  {
   "text": "Chikpo Movement",
   "url": "https://www.yesmagazine.org/issue/nature/2019/05/03/vandana-shiva-seed-saving-forest-biodiversity"
  },
  {
   "text": "[17]",
   "url": "https://en.wikipedia.org/wiki/Chipko_movement#cite_note-17"
  }
 ],
 "31": [
  {
   "text": "Navigating Microaggressions in Everyday Life",
   "url": "https://www.youtube.com/watch?v=imLb8SCxvsc"
  },
  {
   "text": "Anti-Racist Teaching Practices in Teacher Ed",
   "url": "https://docs.google.com/presentation/d/1hnE2jr5Fpng2gpgh3LjJ1dfgXrB2Dexv4z8sNaMfJPw/edit?usp=sharing"
  }
 ],
 "34": [
  {
   "text": "Origins of Black History Month",
   "url": "https://youtu.be/RUUlstTYCLU"
  }
 ],
 "35": [
  {
   "text": "ARTICLE IN EDSOURCE",
   "url": "https://edsource.org/updates/csu-fullerton-pulls-student-teachers-out-of-district-that-banned-critical-race-theory"
  },
  {
   "text": "article on the university",
   "url": "https://news.fullerton.edu/2022/10/college-of-education-supports-just-equitable-and-inclusive-teaching/"
  },
  {
   "text": "resolution",
   "url": "https://4.files.edl.io/c30b/04/06/22/194827-8344512a-9061-418d-a3f9-14e0b380fdb4.pdf"
  }
 ],
 "36": [
  {
   "text": "CCEAL.org",
   "url": "https://www.cceal.org/"
  },
  {
   "text": "▶ Watch video",
   "url": "https://www.youtube.com/watch?v=HlYorKDPXo0"
  }
 ],
 "37": [
  {
   "text": "Know how you will teach race related topics",
   "url": "https://www.latimes.com/california/story/2022-04-06/critical-race-theory-banned-by-an-orange-county-school-board?link_id=5&can_id=b990a6bcca2a3dc64670b83e29dcdcbf&source=email-teach-american-history-in-our-schools-not-just-straight-white-history&email_referrer=email_1512101&email_subject=teach-american-history-in-our-schools-not-just-straight-white-history"
  },
  {
   "text": "increasing number of states",
   "url": "https://abcnews.go.com/Politics/map-anti-critical-race-theory-efforts-reached/story?id=83619715"
  }
 ],
 "38": [
  {
   "text": "Interview by Constanza Eliana",
   "url": "https://www.youtube.com/watch?v=Y0uEuesELmg"
  }
 ],
 "39": [
  {
   "text": "abolitionistteachingnetwork.org",
   "url": "https://abolitionistteachingnetwork.org/resources-for-agitators"
  }
 ],
 "42": [
  {
   "text": "kqed.org",
   "url": "https://www.kqed.org/news/11830384/how-the-longest-student-strike-in-u-s-history-created-ethnic-studies"
  }
 ],
 "43": [
  {
   "text": "Bringing Our Humanity to the TK-5 Classroom Through an Ethnic Studies Stance",
   "url": "https://www.youtube.com/watch?v=K8Vg2WYHrIA"
  }
 ],
 "44": [
  {
   "text": "https://www.youtube.com/watch?v=K8Vg2WYHrIA",
   "url": "https://www.youtube.com/watch?v=K8Vg2WYHrIA"
  }
 ],
 "45": [
  {
   "text": "▶ Watch video",
   "url": "https://www.youtube.com/live/K8Vg2WYHrIA?feature=share"
  }
 ],
 "46": [
  {
   "text": "webinar",
   "url": "https://www.youtube.com/live/K8Vg2WYHrIA?feature=share"
  }
 ],
 "47": [
  {
   "text": "teachinglatinamericathroughliterature.wordpress.com",
   "url": "https://teachinglatinamericathroughliterature.wordpress.com/"
  }
 ],
 "49": [
  {
   "text": "Slideshow",
   "url": "https://docs.google.com/presentation/d/1o4Y-s6KPMKDRWdar1NQ6XWhSFgqS79A4DwR8Xp5Qrvg/edit?usp=sharing"
  },
  {
   "text": "5th-6th grade lesson plan",
   "url": "https://docs.google.com/document/d/1OgGVMJfXYXXlLsdWscraFAirsm5RJXvtUjAToqCsXg4/edit?usp=sharing"
  }
 ],
 "53": [
  {
   "text": "Play & Arts Graph:",
   "url": "https://docs.google.com/presentation/d/1olu6sTLmwJn8xMMJ-KaatSDYNaGRcUEB/edit?usp=sharing&ouid=117033629073427580232&rtpof=true&sd=true"
  }
 ],
 "54": [
  {
   "text": "XY Play Graph: Journeying Backwards",
   "url": "https://docs.google.com/presentation/d/1olu6sTLmwJn8xMMJ-KaatSDYNaGRcUEB/edit?usp=sharing&ouid=117033629073427580232&rtpof=true&sd=true"
  }
 ],
 "56": [
  {
   "text": "4-min video on how crucial play is in the early years.",
   "url": "https://vimeo.com/366806783/ceb4636705"
  }
 ],
 "57": [
  {
   "text": "Play",
   "url": "http://www.amazon.com/Play-Shapes-Brain-Imagination-Invigorates/dp/1583333789/ref=sr_1_1?s=books&ie=UTF8&qid=1402494686&sr=1-1&keywords=play"
  },
  {
   "text": "Read more by Elena Aguilar",
   "url": "https://www.edutopia.org/blog/summer-professional-development-play-elena-aguilar"
  }
 ],
 "59": [
  {
   "text": "Titus Kaphar: How Can We Address Centuries of Racism In Art?",
   "url": "https://www.npr.org/2017/11/10/562836477/titus-kaphar-how-can-we-address-centuries-of-racism-in-art"
  }
 ],
 "60": [
  {
   "text": "Marvel’s New Comic Princess Is Racist As Hell | The Amber Ruffin Show",
   "url": "https://www.youtube.com/watch?v=eG2FbfqGnhk"
  },
  {
   "text": "Sita Sings the Blues",
   "url": "https://www.youtube.com/watch?v=RzTg7YXuy34&t=4612s"
  },
  {
   "text": "EVERYTHING CULTURALLY RIGHT AND WRONG WITH MULAN 1998",
   "url": "https://www.youtube.com/watch?v=8SHC7CnmErM"
  },
  {
   "text": "EVERYTHING CULTURALLY WRONG WITH MULAN 2020 (And How They Could've Been Fixed)",
   "url": "https://www.youtube.com/watch?v=N3QKq24e0HM"
  }
 ],
 "61": [
  {
   "text": "Pocahontas",
   "url": "https://www.theatlantic.com/entertainment/archive/2015/06/revisiting-pocahontas/396626/"
  },
  {
   "text": "-Women’s Media Center",
   "url": "https://womensmediacenter.com/fbomb/disney-added-a-disclaimer-before-racist-depictions-in-its-content"
  }
 ],
 "62": [
  {
   "text": "thinking dispositions",
   "url": "https://pz.harvard.edu/resources/thinking-dispositions"
  },
  {
   "text": "Harvard’s Project Zero",
   "url": "https://pz.harvard.edu/who-we-are/about"
  },
  {
   "text": "READ MORE",
   "url": "https://www.edutopia.org/article/boosting-critical-thinking-across-curriculum"
  },
  {
   "text": "Jorge Valenzuela",
   "url": "https://www.edutopia.org/profile/jorge-valenzuela"
  },
  {
   "text": "Visible thinking",
   "url": "https://pz.harvard.edu/projects/visible-thinking"
  },
  {
   "text": "visible learning research by John Hattie",
   "url": "https://us.corwin.com/en-us/nam/the-visible-learning-research?utm_source=google&utm_medium=cpc&utm_campaign=AVLN21B31&gclid=Cj0KCQiAu62QBhC7ARIsALXijXS0rP7fbbiQFlx4W_cFOQJEhwxQeDpEBOPE9sCY7ZitAhsth-oRONIaAsLxEALw_wcB"
  }
 ],
 "66": [
  {
   "text": "JusticexDesign",
   "url": "https://pz.harvard.edu/projects/justicexdesign"
  },
  {
   "text": "the Agency",
   "url": "http://www.agencybydesign.org/explore-the-framework"
  },
  {
   "text": "Voice, Choice & Mending",
   "url": "https://pz.harvard.edu/sites/default/files/Voice%2C%20Choice%2C%20and%20Mending_0.pdf"
  }
 ],
 "67": [
  {
   "text": "A Mini Design Thinking Project",
   "url": "https://docs.google.com/document/d/1YaU-o-IlHjVdTsgGZ2Grk7nZFo0Yo2SiX43v9pHkN_w/edit#heading=h.djqx9fuye51c"
  }
 ],
 "68": [
  {
   "text": "There’s no I in Teacher: 8 Tips for Collaborative Planning",
   "url": "https://www.edutopia.org/blog/rules-of-thumb-collaborative-planning-rebecca-rufo-tepper"
  },
  {
   "text": "Edutopia.org",
   "url": "https://www.edutopia.org/topic/design-thinking"
  }
 ],
 "70": [
  {
   "text": "favianna.com",
   "url": "https://favianna.com/"
  }
 ],
 "71": [
  {
   "text": "Favianna Rodriguez",
   "url": "https://docs.google.com/presentation/d/1o4Y-s6KPMKDRWdar1NQ6XWhSFgqS79A4DwR8Xp5Qrvg/edit?usp=sharing"
  },
  {
   "text": "poster PDs",
   "url": "https://favianna.com"
  }
 ],
 "72": [
  {
   "text": "Black Lives Matter Week of Action in Art",
   "url": "https://docs.google.com/presentation/d/1HcBmBDDcSkHpbiG-4yA4U7a0sWU9TZwt/edit?usp=sharing&ouid=117033629073427580232&rtpof=true&sd=true"
  }
 ],
 "73": [
  {
   "text": "Video",
   "url": "https://www.youtube.com/watch?v=ML2dRP9i3FQ"
  }
 ],
 "74": [
  {
   "text": "1619 Project",
   "url": "https://pulitzercenter.org/lesson-plan-grouping/1619-project-curriculum"
  },
  {
   "text": "Nikole Hannah-Jones",
   "url": "https://www.youtube.com/watch?v=RKsrtIi-uEM"
  }
 ],
 "75": [
  {
   "text": "Tennessee’s law banning “divisive concepts” in the classroom",
   "url": "https://www.tn.gov/content/dam/tn/education/legal/Prohibited%20Concepts%20in%20Instruction%20Rule%207.29.21%20FINAL.pdf"
  }
 ],
 "76": [
  {
   "text": "Click here for link to slideshow",
   "url": "https://docs.google.com/presentation/d/1jmF9uvhXfQvnr_41V2FOner3cQUv2qGi/edit?usp=sharing&ouid=117033629073427580232&rtpof=true&sd=true"
  }
 ],
 "78": [
  {
   "text": "This Florida teen went viral for his lesson on the Stonewall riots",
   "url": "https://www.washingtonpost.com/lifestyle/2022/04/04/florida-teen-stonewall-riots-history-lesson/?link_id=4&can_id=b990a6bcca2a3dc64670b83e29dcdcbf&source=email-teach-american-history-in-our-schools-not-just-straight-white-history&email_referrer=email_1512101&email_subject=teach-american-history-in-our-schools-not-just-straight-white-history"
  },
  {
   "text": "signed the Parental Rights in Education bill",
   "url": "https://www.washingtonpost.com/politics/dont-say-gay-bill-given-to-florida-gov-ron-desantis/2022/03/28/63ff6d9c-aeb9-11ec-9dbd-0d4609d44c1c_story.html?itid=lk_inline_manual_2"
  }
 ],
 "79": [
  {
   "text": "TheDeciderApp",
   "url": "https://thedecider.app/side-by-side-comparison"
  },
  {
   "text": "history of youth-led movements",
   "url": "https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1Gb0pxJvQFAmOaIixYPzljrM2iCTysEkOwV3rJBbA97A"
  },
  {
   "text": "Lesson plan",
   "url": "https://cdn.kqed.org/wp-content/uploads/sites/26/2018/03/Youth-Activism-is-Nothing-New-lesson-plan.pdf"
  }
 ],
 "80": [
  {
   "text": "@slamberkeleyhigh",
   "url": "https://www.instagram.com/slamberkeleyhigh/"
  },
  {
   "text": "@PittsburgProdigies",
   "url": "https://instagram.com/pittsburgprodigies"
  },
  {
   "text": "@ahs.youth.voice",
   "url": "https://www.instagram.com/ahs.youth.voice/"
  },
  {
   "text": "@campo_pac_club",
   "url": "https://www.instagram.com/campo_pac_club/"
  },
  {
   "text": "https://www.bayareacreative.org/sparcpoetry",
   "url": "https://www.bayareacreative.org/sparcpoetry"
  },
  {
   "text": "@GetLitPoet",
   "url": "https://www.instagram.com/getlitpoet/"
  },
  {
   "text": "@mehs_poets",
   "url": "https://www.instagram.com/mehs_poets/"
  },
  {
   "text": "https://youthspeaks.org",
   "url": "https://youthspeaks.org"
  },
  {
   "text": "Street Dance Curriculum",
   "url": "https://destinyarts.org/street-dance-curriculum/"
  },
  {
   "text": "Slam Club Handbook",
   "url": "https://docs.google.com/document/d/1VtUdTCwaNsjj0PofgWFM7RqXtjOD8BMOfTV_6HGW6S4/edit"
  },
  {
   "text": "@YouthSpeaks",
   "url": "https://instagram.com/youthspeaks"
  }
 ],
 "82": [
  {
   "text": "Children Are Citizens",
   "url": "https://pz.harvard.edu/projects/children-are-citizens"
  },
  {
   "text": "Research story",
   "url": "https://www.gse.harvard.edu/news/uk/15/04/kid-nation#sthash.1V23Ubty.dpuf"
  }
 ],
 "83": [
  {
   "text": "http://studentvoicescampaign.org",
   "url": "http://studentvoicescampaign.org"
  }
 ],
 "84": [
  {
   "text": "https://soundout.org",
   "url": "https://soundout.org"
  }
 ],
 "85": [
  {
   "text": "Alphabet Rockers",
   "url": "https://www.alphabetrockers.com/"
  },
  {
   "text": "music videos",
   "url": "https://www.alphabetrockers.com/videos"
  }
 ],
 "86": [
  {
   "text": "alphabetrockers.com",
   "url": "https://www.alphabetrockers.com/videos"
  }
 ],
 "87": [
  {
   "text": "unicef.org",
   "url": "https://www.unicef.org/reports/convention-rights-child-children-version"
  }
 ],
 "90": [
  {
   "text": "Voices of Youth in Chicago Education",
   "url": "http://voyceproject.org"
  },
  {
   "text": "Black Organizing Project",
   "url": "https://blackorganizingproject.org/our-response-to-the-madison-park-academy-incident/"
  },
  {
   "text": "Beautiful Trouble",
   "url": "https://beautifultrouble.org/strategy-cards"
  },
  {
   "text": "https://www.innercitystruggle.org",
   "url": "https://www.innercitystruggle.org"
  },
  {
   "text": "Too Young to Vote, Old Enough to Act:",
   "url": "https://www.kqed.org/lowdown/30275/the-kids-are-all-right-a-timeline-of-youth-led-movements-that-changed-the-nation"
  },
  {
   "text": "PoliceFreeSchools.org",
   "url": "https://policefreeschools.org"
  },
  {
   "text": "Design an Action",
   "url": "https://docs.google.com/document/d/16HjQZAnc8qI3qN14pF4_jw6_0LFTx4o5JUncMDeeO0E/edit"
  },
  {
   "text": "Rethinking Schools",
   "url": "https://rethinkingschools.org"
  },
  {
   "text": "Zinn Education Project",
   "url": "https://www.zinnedproject.org"
  }
 ],
 "94": [
  {
   "text": "Educator’s Guide",
   "url": "https://teachinglatinamericathroughliterature.wordpress.com/march-2014-the-lightning-dreamer-cubas-greatest-abolitionist/"
  },
  {
   "text": "Rhythm and Resistance: Teaching Poetry for Social Justice",
   "url": "http://www.rethinkingschools.org/proddetails.asp?ID=9780942961614"
  }
 ],
 "95": [
  {
   "text": "still images",
   "url": "https://dramaresource.com/freeze-frames/"
  },
  {
   "text": "The Rainbow of Desire",
   "url": "https://amzn.to/3v0GjRp"
  },
  {
   "text": "Drama Games for Classroom Use",
   "url": "https://dramaresource.com/drama-games/"
  }
 ],
 "98": [
  {
   "text": "Google",
   "url": "https://docs.google.com/presentation/d/1hfCFZbRcvkOzw4SvT8Z3yC_RxafV2n1V/edit?usp=sharing&ouid=117033629073427580232&rtpof=true&sd=true"
  }
 ],
 "101": [
  {
   "text": "Keezy",
   "url": "https://apps.apple.com/us/app/keezy-classic/id605855595"
  },
  {
   "text": "Jungle Music",
   "url": "https://play.google.com/store/apps/details?id=air.junglemusic&hl=en_US&gl=US"
  },
  {
   "text": "demo",
   "url": "https://www.youtube.com/watch?v=qbZoEmj4UL4"
  },
  {
   "text": "How-To",
   "url": "https://www.youtube.com/watch?v=hVa2IKMe62s"
  },
  {
   "text": "MUSIC MAKING APPS FOR CHILDREN",
   "url": "https://docs.google.com/document/d/1gcCwTqosf4d_iGz6fhBhL9yVe9i8ldJA/edit"
  },
  {
   "text": "Music App Recommendations for Kids",
   "url": "https://www.youtube.com/watch?v=O5hZm8CbOtA"
  },
  {
   "text": "10 Music-Making Apps",
   "url": "https://tinybeans.com/best-music-making-apps-for-kids/slide/1"
  },
  {
   "text": "Kapu Bloom Tunes",
   "url": "https://apps.apple.com/us/app/kapu-bloom-tunes/id920305238"
  },
  {
   "text": "Demo",
   "url": "https://www.youtube.com/watch?v=dIQgYX0jlc8"
  },
  {
   "text": "Hello Everybody",
   "url": "https://apps.apple.com/us/app/hello-everybody/id1019486012"
  },
  {
   "text": "Music Together website",
   "url": "https://www.musictogether.com/hello-everybody-app"
  }
 ],
 "102": [
  {
   "text": "Árbol de Música slideshow",
   "url": "https://docs.google.com/presentation/d/1yb1QK6XY3LYZEK-UrsGvV-dAxuhxXmuYI_4Dk71EtaE/edit?usp=sharing"
  }
 ],
 "104": [
  {
   "text": "DramaResource.com",
   "url": "https://dramaresource.com/drama-games/"
  }
 ],
 "107": [
  {
   "text": "Guide to terms for gender identity and sexual orientation",
   "url": "https://www.washingtonpost.com/lifestyle/2022/04/01/gender-identity-glossary/"
  }
 ],
 "108": [
  {
   "text": "Guide",
   "url": "https://hrc-prod-requests.s3-us-west-2.amazonaws.com/files/documents/Supporting-Caring-for-Trans-Children-UPDTE-100424.pdf"
  }
 ],
 "110": [
  {
   "text": "Video read-aloud of book",
   "url": "https://www.youtube.com/watch?v=ikfUujgFdYA"
  }
 ],
 "111": [
  {
   "text": "bookshop.org",
   "url": "https://bookshop.org/books/when-harley-has-anxiety-a-fun-cbt-skills-activity-book-to-help-manage-worries-and-fears-for-kids-5-9/9780593435458?gclid=Cj0KCQjwg_iTBhDrARIsAD3Ib5gnCnUYGBkhYZ9y9rDE1N8dbQwC88RFGpYC6epVnKHvi3p384JPIuEaAtxFEALw_wcB"
  }
 ],
 "112": [
  {
   "text": "books.google.com",
   "url": "https://books.google.com/books?id=xpIfCwAAQBAJ&printsec=frontcover&source=gbs_ViewAPI&hl=en#v=onepage&q&f=false"
  }
 ],
 "113": [
  {
   "text": "Safe spaces for kids in school classrooms",
   "url": "https://www.pinterest.co.uk/pin/173599760626151823/"
  },
  {
   "text": "Creating a teen safe space in schools",
   "url": "https://www.pinterest.co.uk/search/pins/?q=teen%20safe%20spaces%20in%20schools&rs=typed&term_meta%5B%5D=teen%20safe%20spaces%20in%20schools%7Ctyped"
  }
 ],
 "114": [
  {
   "text": "secondsale.com",
   "url": "https://www.secondsale.com/p/cbt-workbook-for-kids-40-fun-exercises-and-activities-to-help-children-overcome-anxiety-face-their-fears-at-home-at-school-and-out-in-the-world/1526043?ean13=9781641523493&campaignid=12417785642&adgroupid=121223596947&keyword=&device=c&gclid=Cj0KCQjwg_iTBhDrARIsAD3Ib5h5s-3YOpHIl6Eagno0MjzmEA-sC0yl3eNYye9T7Ys8BAT1HUKNkM0aAhcKEALw_wcB"
  }
 ],
 "121": [
  {
   "text": "SCORECARD",
   "url": "https://drive.google.com/drive/folders/1gYJikeDQPWcrLD-GhwAgWh0TvBvyPnHR"
  }
 ],
 "122": [
  {
   "text": "Scorecard_Culturally Responsive Curriculum",
   "url": "https://drive.google.com/drive/folders/1gYJikeDQPWcrLD-GhwAgWh0TvBvyPnHR"
  }
 ],
 "123": [
  {
   "text": "Scorecard_Culturally Responsive Curriculum",
   "url": "https://drive.google.com/drive/folders/1gYJikeDQPWcrLD-GhwAgWh0TvBvyPnHR"
  }
 ],
 "124": [
  {
   "text": "See Think Me We",
   "url": "https://pz.harvard.edu/resources/see-think-me-we"
  }
 ],
 "125": [
  {
   "text": "Making Learning Visible",
   "url": "https://pz.harvard.edu/projects/making-learning-visible"
  },
  {
   "text": "Edutopia",
   "url": "https://www.edutopia.org"
  },
  {
   "text": "Center for Ecoliteracy",
   "url": "https://www.ecoliteracy.org/article/great-turning"
  }
 ],
 "128": [
  {
   "text": "Girls Inc. of Alameda County",
   "url": "https://girlsinc-alameda.org"
  },
  {
   "text": "Eureka!",
   "url": "https://twitter.com/GirlsIncAC/status/1516846359114313729/photo/1"
  },
  {
   "text": "t.co",
   "url": "https://t.co/jSDKUPWTyX"
  },
  {
   "text": "http://",
   "url": "http://ow.ly/JSRI50IfmIZ"
  }
 ]
};
const CT_SLIDE_COUNT = 133;
if (typeof window !== 'undefined') { window.CT_MEDIA = CT_MEDIA; window.CT_SLIDE_LINKS = CT_SLIDE_LINKS; window.CT_SLIDE_COUNT = CT_SLIDE_COUNT; }
