/* ============================================================
   Courageous Teachers — interactions
   Shared across index.html and resources.html. Each block
   guards on the elements it needs, so one file serves both.
   ============================================================ */
(function () {
  'use strict';
  const { TOPICS, TYPES, GRADES, RESOURCES, HERO_QUOTES, INTRO_QUESTIONS } = window.CT;

  const topicById = Object.fromEntries(TOPICS.map(t => [t.id, t]));
  const typeById  = Object.fromEntries(TYPES.map(t => [t.id, t]));
  const gradeById = Object.fromEntries(GRADES.map(g => [g.id, g]));
  const el = id => document.getElementById(id);
  const MEDIA = window.CT_MEDIA || {};          // generated by scripts/build-images.js
  const SLIDE_LINKS = window.CT_SLIDE_LINKS || {};
  const medOf = id => MEDIA[id] || null;
  const slideURL = n => `assets/slides/slide-${String(n).padStart(3, '0')}.jpg`;
  const linksForSlide = n => (n && SLIDE_LINKS[n]) || [];
  const linksForRes = id => { const m = medOf(id); return m ? linksForSlide(m.slideNum) : []; };
  const linkItems = arr => arr.map(l =>
    `<li><a href="${l.url}" target="_blank" rel="noopener">${l.text}</a></li>`).join('');

  /* ---------- mobile nav ---------- */
  const burger = document.querySelector('.hamburger');
  const links = document.querySelector('.nav-links');
  if (burger && links) burger.addEventListener('click', () => links.classList.toggle('open'));

  /* ---------- hero quote rotation (index) ---------- */
  const hq = el('heroQuote');
  if (hq) {
    let i = 0;
    setInterval(() => {
      hq.classList.add('fading');
      setTimeout(() => {
        i = (i + 1) % HERO_QUOTES.length;
        el('hqText').textContent = HERO_QUOTES[i].q;
        el('hqCite').textContent = HERO_QUOTES[i].a;
        hq.classList.remove('fading');
      }, 500);
    }, 4500);
  }

  /* ---------- intro questions (index) ---------- */
  const qGrid = el('qGrid');
  if (qGrid) {
    qGrid.innerHTML = INTRO_QUESTIONS
      .map(q => `<div class="q-chip">${q}</div>`).join('');
  }

  /* ---------- topic grid (index) ---------- */
  const topicGrid = el('topicGrid');
  if (topicGrid) {
    topicGrid.innerHTML = TOPICS.map((t, n) => `
      <a class="topic-card" style="--tc:${t.color}" href="resources.html#topic/${t.id}">
        <div class="tnum">${String(n + 1).padStart(2, '0')}</div>
        <h3>${t.n}</h3>
        <p>${t.blurb}</p>
        <div class="go">Open ${countByTopic(t.id)} resources →</div>
      </a>`).join('');
  }
  function countByTopic(id) { return RESOURCES.filter(r => r.topic === id).length; }

  /* ============================================================
     SLIDE LIGHTBOX — shared by cards, modal, and gallery page.
     Defined before the library guard so the gallery page gets it too.
     ============================================================ */
  let lbList = [], lbIdx = 0;
  const lb = el('lightbox');
  function openLightbox(slideNum, list) {
    lbList = (list && list.length) ? list : [slideNum];
    lbIdx = Math.max(0, lbList.indexOf(slideNum));
    showLb(); lb.classList.add('open'); document.body.style.overflow = 'hidden';
  }
  function showLb() {
    const n = lbList[lbIdx];
    const html = window.CT_SLIDE_HTML && window.CT_SLIDE_HTML[n];  // faithful HTML (real text + inline links)
    el('lbStage').innerHTML = html || `<img src="${slideURL(n)}" alt="Slide ${n}">`;  // fallback to flat JPG
    el('lbCaption').textContent = `Slide ${n} of ${window.CT_SLIDE_COUNT || lbList.length}`;
    const multi = lbList.length > 1 ? 'visible' : 'hidden';
    el('lbPrev').style.visibility = multi; el('lbNext').style.visibility = multi;
    const lk = linksForSlide(n);            // make the links ON this slide clickable
    const box = el('lbLinks');
    if (box) {
      box.innerHTML = lk.length
        ? `<div class="lb-links-head">Links on this slide</div><ul class="links-list">${linkItems(lk)}</ul>` : '';
      box.style.display = lk.length ? 'block' : 'none';
    }
  }
  function stepLb(d) { lbIdx = (lbIdx + d + lbList.length) % lbList.length; showLb(); }
  function closeLb() {
    lb.classList.remove('open');
    const modalOpen = el('modalBg') && el('modalBg').classList.contains('open');
    if (!modalOpen) document.body.style.overflow = '';
  }
  if (lb) {
    el('lbClose').addEventListener('click', closeLb);
    el('lbPrev').addEventListener('click', () => stepLb(-1));
    el('lbNext').addEventListener('click', () => stepLb(1));
    lb.addEventListener('click', e => { if (e.target === lb) closeLb(); });
    document.addEventListener('keydown', e => {
      if (!lb.classList.contains('open')) return;
      if (e.key === 'Escape') closeLb();
      if (e.key === 'ArrowLeft') stepLb(-1);
      if (e.key === 'ArrowRight') stepLb(1);
    });
  }

  /* ---------- gallery page (slides.html): grid of all slides ---------- */
  const grid = el('slideGrid');
  if (grid) {
    const total = window.CT_SLIDE_COUNT || 0;
    const all = Array.from({ length: total }, (_, i) => i + 1);
    grid.innerHTML = all.map(n =>
      `<button class="slide-thumb" data-n="${n}"><img src="${slideURL(n)}" alt="Slide ${n}" loading="lazy"><span>${n}</span></button>`).join('');
    grid.querySelectorAll('.slide-thumb').forEach(b =>
      b.addEventListener('click', () => openLightbox(+b.dataset.n, all)));
  }

  /* ============================================================
     LIBRARY (resources.html)
     ============================================================ */
  const cardsEl = el('cards');
  if (!cardsEl) return;

  const state = { search: '', types: new Set(), topics: new Set(), grades: new Set() };

  /* build filter chips */
  buildChips(el('typeFilters'), TYPES, state.types, 'type', t =>
    `<span class="swatch" style="background:${t.color}"></span>${t.n}`);
  buildChips(el('topicFilters'), TOPICS, state.topics, 'topic', t => t.n);
  buildChips(el('gradeFilters'), GRADES, state.grades, 'grade', g => g.n);

  function buildChips(container, items, set, kind, label) {
    items.forEach(item => {
      const b = document.createElement('button');
      b.className = 'chip';
      b.dataset.id = item.id;
      b.innerHTML = label(item);
      if (kind === 'type') b.style.setProperty('--ca', item.color);
      b.addEventListener('click', () => {
        if (set.has(item.id)) { set.delete(item.id); b.classList.remove('active', 'type-active'); }
        else { set.add(item.id); b.classList.add('active'); if (kind === 'type') b.classList.add('type-active'); }
        render();
      });
      container.appendChild(b);
    });
  }

  /* search */
  const searchInput = el('search');
  searchInput.addEventListener('input', e => { state.search = e.target.value.toLowerCase().trim(); render(); });

  /* clear */
  const clearBtn = el('clearBtn');
  clearBtn.addEventListener('click', () => {
    state.search = ''; searchInput.value = '';
    state.types.clear(); state.topics.clear(); state.grades.clear();
    document.querySelectorAll('.chip.active').forEach(c => c.classList.remove('active', 'type-active'));
    render();
  });

  /* deep link: #topic/<id> preselects a topic */
  function applyHash() {
    const m = location.hash.match(/^#topic\/(.+)$/);
    if (m && topicById[m[1]]) {
      state.topics.add(m[1]);
      const chip = document.querySelector(`#topicFilters .chip[data-id="${m[1]}"]`);
      if (chip) chip.classList.add('active');
    }
    const rm = location.hash.match(/^#r\/(.+)$/);
    if (rm) { const r = RESOURCES.find(x => x.id === rm[1]); if (r) openModal(r); }
  }

  function matches(r) {
    if (state.types.size && !state.types.has(r.type)) return false;
    if (state.topics.size && !state.topics.has(r.topic)) return false;
    if (state.grades.size) {
      const has = r.grades.includes('all') || r.grades.some(g => state.grades.has(g));
      if (!has) return false;
    }
    if (state.search) {
      const hay = [r.title, r.body, r.source || '', topicById[r.topic].n,
                   typeById[r.type].n, r.voices.join(' ')].join(' ').toLowerCase();
      if (!hay.includes(state.search)) return false;
    }
    return true;
  }

  function gradeLabel(r) {
    if (r.grades.includes('all')) return 'All grades';
    return r.grades.map(g => gradeById[g] ? gradeById[g].n : g).join(' · ');
  }

  function render() {
    const list = RESOURCES.filter(matches);
    el('count').textContent = `${list.length} of ${RESOURCES.length} resources`;
    const anyFilter = state.search || state.types.size || state.topics.size || state.grades.size;
    clearBtn.hidden = !anyFilter;

    el('empty').hidden = list.length !== 0;
    cardsEl.innerHTML = list.map(r => {
      const tp = topicById[r.topic], ty = typeById[r.type];
      const voice = r.voices[0] ? `<span class="voice-pill">${r.voices[0]}${r.voices.length > 1 ? ' +' + (r.voices.length - 1) : ''}</span>` : '';
      const im = medOf(r.id);
      const cover = im && im.cover
        ? `<div class="card-cover"><img src="${im.cover}" alt="" loading="lazy"></div>` : '';
      const nLinks = linksForRes(r.id).length;
      const linkBadge = nLinks ? `<span class="link-badge">🔗 ${nLinks}</span>` : '';
      return `
        <article class="card${cover ? ' has-cover' : ''}" style="--cc:${tp.color}" data-id="${r.id}">
          ${linkBadge}
          ${cover}
          <div class="meta-top">
            <span class="type-tag" style="background:${ty.color}">${ty.n}</span>
            <span class="topic-tag">${tp.n}</span>
          </div>
          <h3>${r.title}</h3>
          <p class="excerpt">${stripQuotes(r.body)}</p>
          <div class="meta-bot">
            <span class="grade-pill">${gradeLabel(r)}</span>
            ${voice}
          </div>
        </article>`;
    }).join('');

    cardsEl.querySelectorAll('.card').forEach(c =>
      c.addEventListener('click', () => openModal(RESOURCES.find(r => r.id === c.dataset.id))));
  }

  function stripQuotes(s) { return s.replace(/^[“"]/, '').slice(0, 220); }

  /* ---------- modal ---------- */
  const modalBg = el('modalBg');
  function openModal(r) {
    const tp = topicById[r.topic], ty = typeById[r.type];
    el('modalTop').style.background = tp.color;
    const voices = r.voices.length
      ? `<div class="voices-row">${r.voices.map(v => `<span class="voice-pill">❝ ${v}</span>`).join('')}</div>` : '';
    const im = medOf(r.id);
    const hasSlide = im && im.slideNum;
    const cover = im && im.cover
      ? `<div class="modal-cover${hasSlide ? ' clickable' : ''}"${hasSlide ? ` data-slide="${im.slideNum}"` : ''}><img src="${im.cover}" alt="">${hasSlide ? '<span class="cover-hint">More…</span>' : ''}</div>` : '';
    const resLinks = linksForRes(r.id);
    const links = resLinks.length
      ? `<div class="links-block"><div class="links-head">Resources &amp; links from this slide</div>
         <ul class="links-list">${linkItems(resLinks)}</ul></div>` : '';
    const moreBtn = hasSlide
      ? `<button class="slide-link" data-slide="${im.slideNum}">More…</button>` : '';
    el('modalBody').innerHTML = `
      ${cover}
      <div class="meta-top">
        <span class="type-tag" style="background:${ty.color}">${ty.n}</span>
        <span class="topic-tag">${tp.n} · ${gradeLabel(r)}</span>
      </div>
      <h2>${r.title}</h2>
      <div class="full">${r.body}</div>
      ${voices}
      ${links}
      ${r.source ? `<div class="src"><strong>Source:</strong> ${r.source}</div>` : ''}
      ${moreBtn}`;
    el('modalBody').querySelectorAll('[data-slide]').forEach(node =>
      node.addEventListener('click', () => openLightbox(+node.dataset.slide)));
    modalBg.classList.add('open');
    document.body.style.overflow = 'hidden';
    history.replaceState(null, '', '#r/' + r.id);
  }
  function closeModal() {
    modalBg.classList.remove('open');
    document.body.style.overflow = '';
    history.replaceState(null, '', location.pathname);
  }
  el('modalClose').addEventListener('click', closeModal);
  modalBg.addEventListener('click', e => { if (e.target === modalBg) closeModal(); });
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });

  applyHash();
  render();
})();
