#!/usr/bin/env node
/* ============================================================
   build-videos.js   (run: node scripts/build-videos.js)
   Harvests every YouTube link scattered across the deck (from the
   per-slide link map in js/images.js) into ONE video gallery feed.
   Nicole's videos live on slides all over the deck — there's no
   single playlist — so this gathers them in one place.

   For each unique video it fetches YouTube's public oEmbed data
   (real title + channel) so the gallery shows proper titles instead
   of the deck's ad-hoc link text ("Video", "demo", "7 minute video").
   No API key required. Deleted/private videos are kept but flagged.

   Output: js/videos.js  (window.CT_VIDEOS — sorted by first slide)
   ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');

// load the per-slide link map without a browser
const sandbox = { window: {} };
require('vm').runInNewContext(fs.readFileSync(path.join(ROOT, 'js/images.js'), 'utf8'), sandbox);
const SLIDE_LINKS = sandbox.window.CT_SLIDE_LINKS || {};

const YT = /(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/|live\/)|youtu\.be\/)([\w-]{11})/;

// gather unique videos: id -> { id, slides[], texts[] }
const vids = new Map();
for (const slide of Object.keys(SLIDE_LINKS)) {
  for (const l of SLIDE_LINKS[slide]) {
    const m = (l.url || '').match(YT);
    if (!m) continue;
    const id = m[1];
    if (!vids.has(id)) vids.set(id, { id, slides: [], texts: [] });
    const v = vids.get(id);
    if (!v.slides.includes(+slide)) v.slides.push(+slide);
    const t = (l.text || '').replace(/\s+/g, ' ').trim();
    if (t && !/^(video|watch video|▶|here|demo|how-to)$/i.test(t) && !v.texts.includes(t)) v.texts.push(t);
  }
}

function oembed(id) {
  const url = `https://www.youtube.com/oembed?format=json&url=${encodeURIComponent('https://www.youtube.com/watch?v=' + id)}`;
  try {
    const out = execSync(`curl -sS --max-time 20 ${JSON.stringify(url)}`, { encoding: 'utf8' }).trim();
    if (!out || out[0] !== '{') return null;          // 401/404 => not JSON
    return JSON.parse(out);
  } catch { return null; }
}

const list = [...vids.values()].sort((a, b) => Math.min(...a.slides) - Math.min(...b.slides));
let live = 0, dead = 0;
const CT_VIDEOS = list.map(v => {
  const o = oembed(v.id);
  const fallback = v.texts[0] || '';
  if (o && o.title) {
    live++;
    return { id: v.id, title: o.title, channel: o.author_name || '', slides: v.slides, available: true };
  }
  dead++;
  process.stderr.write(`  unavailable: ${v.id} (slides ${v.slides.join(',')})\n`);
  return { id: v.id, title: fallback || 'Video (unavailable)', channel: '', slides: v.slides, available: false };
});

const banner = `/* AUTO-GENERATED by scripts/build-videos.js — do not edit by hand.
   CT_VIDEOS: every YouTube link in the deck, gathered into one gallery feed.
   Re-run after the deck changes: node scripts/build-videos.js */\n`;
fs.writeFileSync(path.join(ROOT, 'js/videos.js'),
  banner + 'const CT_VIDEOS = ' + JSON.stringify(CT_VIDEOS) + ';\n' +
  "if (typeof window !== 'undefined') window.CT_VIDEOS = CT_VIDEOS;\n");

console.log(`Gathered ${CT_VIDEOS.length} videos -> js/videos.js  (${live} live, ${dead} unavailable)`);
